name = "omnichat"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat", "streams_enable_constructors", "transformstream_enable_standard_constructor"]
pages_build_output_dir = ".vercel/output/static"

# Production environment
[env.production]
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat", "streams_enable_constructors", "transformstream_enable_standard_constructor"]

# Preview environment
[env.preview]
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat", "streams_enable_constructors", "transformstream_enable_standard_constructor"]

# D1 Database Configuration
[[d1_databases]]
binding = "DB"
database_name = "omnichat-db"
database_id = "90dedc77-4561-445e-b7a2-d136e008f42f"


# R2 Storage Configuration
[[r2_buckets]]
binding = "R2"
bucket_name = "omnichat-files"

# KV Namespace for sessions/cache
[[kv_namespaces]]
binding = "KV"
id = "to-be-generated"

# Environment variables (will be set with wrangler secret)
# OPENAI_API_KEY
# ANTHROPIC_API_KEY
# GOOGLE_API_KEY
# CLERK_SECRET_KEY
# STRIPE_SECRET_KEY
# STRIPE_WEBHOOK_SECRET